title: Pix2Pix Colorization (cGan)
description: Pix2Pix colorization using cGan
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
